### ISSUE TITLE
Server Application Crash - TypeError: Cannot use 'in' operator to search for 'message' in header is wrong

### ISSUE THREAD

**Issue by AndyFug** [bitfocus/companion-module-iiyama-prolite#6]
Hi.

We are getting a brief (3 secs or so) Companion server crash when we run this module to control a Iiyama Prolite screen using the LHxx42UHS protocol.

The crash appears to happen when we trigger any action, but in this case when we run a `prolite: Change Input` action, setting the TV input to `HDMI 1`.

I have tried to run this on Companion versions `v3.2.0` and `v3.2.2`, and both behave exactly the same.

Here is the relevant log entries from `~/Library/Application Support/companion/logs/companion-2024-04-04.0.log`:

```
TypeError: Cannot use 'in' operator to search for 'message' in header is wrong
    at t.IpcWrapper.receivedMessage (/Applications/Companion.app/Contents/Resources/main.js:2:2451698)
    at ChildProcess.a (/Applications/Companion.app/Contents/Resources/main.js:2:2792667)
    at ChildProcess.emit (node:events:529:35)
    at ChildProcess.emit (node:domain:489:12)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
sentry error {
    "values": [
        {
            "type": "TypeError",
            "value": "Cannot use 'in' operator to search for 'message' in header is wrong",
            "stacktrace": {
                "frames": [
                    {
                        "filename": "node:internal/process/task_queues",
                        "module": "task_queues",
                        "function": "process.processTicksAndRejections",
                        "lineno": 83,
                        "colno": 21,
                        "in_app": false
                    },
                    {
                        "filename": "node:internal/child_process",
                        "module": "child_process",
                        "function": "emit",
                        "lineno": 944,
                        "colno": 14,
                        "in_app": false
                    },
                    {
                        "filename": "node:domain",
                        "module": "node:domain",
                        "function": "ChildProcess.emit",
                        "lineno": 489,
                        "colno": 12,
                        "in_app": false
                    },
                    {
                        "filename": "node:events",
                        "module": "node:events",
                        "function": "ChildProcess.emit",
                        "lineno": 529,
                        "colno": 35,
                        "in_app": false
                    },
                    {
                        "filename": "app:///main.js",
                        "module": "main",
                        "function": "ChildProcess.a",
                        "lineno": 2,
                        "colno": 2792667,
                        "in_app": true,
                        "pre_context": [
                            "/*! For license information please see main.js.LICENSE.txt */"
                        ],
                        "context_line": "'{snip} message: ${JSON.stringify(e)}`)}),5e3);const a=e=>{this.#H.receivedMessage(e)};r.child.on(\"message\",a),this.#kr=()=>{r.child.off(\"message\",a {snip}",
                        "post_context": []
                    },
                    {
                        "filename": "app:///main.js",
                        "module": "main",
                        "function": "t.IpcWrapper.receivedMessage",
                        "lineno": 2,
                        "colno": 2451698,
                        "in_app": true,
                        "pre_context": [
                            "/*! For license information please see main.js.LICENSE.txt */"
                        ],
                        "context_line": "'{snip} :void 0;if(e.success)t.resolve(r);else{let e=r;r&&\"message\"in r&&(e=new Error(r.message),r.stack&&(e.stack=r.stack)),t.reject(e)}break}defau {snip}",
                        "post_context": []
                    }
                ]
            },
            "mechanism": {
                "type": "onuncaughtexception",
                "handled": false
            }
        }
    ]
}
2024-04-04T14:38:04.202Z Application: Companion exited with code: 1
2024-04-04T14:38:04.203Z Application: Restart Count: 1
2024-04-04T14:38:05.504Z info Log/Controller Application starting
2024-04-04T14:38:05.505Z info Registry Build 3.2.2+6688-stable-7417d2a0
```

There are no useful module log entries in the UI...  probably because the server application itself appears to be the issue here.

**Comment by BryanCrotaz** [comment]
Can you post a bug report in companion, referencing this bug report?

The bug in companion is a meaningless error - it's likely that the module is returning data in a form they don't like - the error should say what the module did wrong. The information that supplies will enable me to fix this.

**Comment by AndyFug** [comment]
Thank you for your prompt response.  

> Can you post a bug report in companion, referencing this bug report?

Apologies... when you say post a bug report in Companion, do you mean there is a mechanism within the server app for doing this or are you just suggesting I post an Issue via the GH repo and reference this Issue from there?

> the error should say what the module did wrong. The information that supplies will enable me to fix this.

Do I need to dig out another log file?  If so, can you point me in the right direction?

**Comment by BryanCrotaz** [comment]
> Apologies... when you say post a bug report in Companion, do you mean there is a mechanism within the server app for doing this or are you just suggesting I post an Issue via the GH repo and reference this Issue from there?

On the GH repo

> > the error should say what the module did wrong. The information that supplies will enable me to fix this.

The information they supply in a better error message. Tag me in your bug report and I'll see any info they give

**Comment by Julusian** [comment]
This is happening because this is throwing a string rather than an error. https://github.com/bitfocus/companion-module-iiyama-prolite/blob/ecdfb68eb4a27413aaf3d01d63476d022b3bc348/src/prolite-api/protocols/LH42UHS.ts#L182
And I didn't think to test that...

So the quick fix is to ensure that anything thrown is an error. I will work on a fix upstream too

**Comment by AndyFug** [comment]
Hi.  Obviously throwing the string is one part of this, but I managed to stop the error being thrown in the first place by [commenting out line 119](https://github.com/bitfocus/companion-module-iiyama-prolite/blob/ecdfb68eb4a27413aaf3d01d63476d022b3bc348/src/prolite-api/protocols/LH42UHS.ts#L119) in the `AckNack` method, which I believe is  causing the `checkReply` method to be called twice.

`checkReply` is already called in the `readReply` method, which slices out some of the message, making it invalid on the second call of `checkReply`.

Hope that helps.

**Comment by BryanCrotaz** [comment]
Well spotted! Submit it as a PR and I'll accept it.
